server:
  port: 8002
mybatis:
  type-aliases-package: com.jiaoyu.springcloud.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
spring:
  application:
    name: dept-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 897570
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  cloud:
    config:
      uri: http://localhost:8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: dept-8002
info:
  app.name: jiaoyu-dept8002
  company.name: www.jiaoyu521.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
